# https://dynamic-data-service.buildify.asia
# http://localhost:3005
@host = https://dynamic-data-service.buildify.asia

### health check
GET {{host}} HTTP/1.1

###
POST {{host}}/api/document HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "collectionId": 9,
  "data": {
    "name": "Document 9 Product",
    "type": "Document 1",
    "title": "Document 2",
    "price": 16
  }
}

###
GET {{host}}/api/document?id=4 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
PUT {{host}}/api/document HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "id": 4,
  "collectionId": 1,
  "data": {
    "name": "Document 1 Product",
    "type": "Document 1",
    "title": "Document 2",
    "price": "Document 3"
  }
}

###
DELETE  {{host}}/api/document?id=4 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
POST {{host}}/api/collection HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "name": "collection 6",
  "projectId": "645a91c1b5d8c898fc762833",
  "dataKeys": ["name","type","title","price"],
  "dataTypes": [1,1,1,2]
}


###
GET {{host}}/api/collection?id=8 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
GET {{host}}/api/collection/list?projectId=645f4128f368d527a885a59e HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlkYW0iLCJleHAiOjIwNDI1MDg4Mzl9.zBli4pyymdcuYTTK3auHvfTdJrdm40EV2Syj0BfUlNs

###
GET {{host}}/api/collection/map?projectId=645a91c1b5d8c898fc762833 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
PUT {{host}}/api/collection HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "id": 3,
  "name": "collection 33",
  "dataKeys": ["name","new","title","price"],
  "dataTypes": [1,1,1,1]
}

###
DELETE  {{host}}/api/collection?id=3 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY


### health check
GET {{host}}