# https://user-service.buildify.asia
# http://localhost:3002
@host = http://localhost:3002

# -------- user ------------

### sign up
POST {{host}}/api/sign-up HTTP/1.1
content-type: application/json

{
    "fullName": "new user",
    "username": "newUser",
    "password": "dada"
}

### sign in
POST {{host}}/api/sign-in HTTP/1.1
content-type: application/json

{
    "username": "newUser",
    "password": "newPass"
}

### get user
GET {{host}}/api/user HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJleHAiOjIwNDIyNzQ1NDB9.PCIjiOy6zmSVm2ilrzlWZctmyBKIRnP1ECSP9G_O2mY


### update user
PUT {{host}}/api/user HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJleHAiOjIwNDIyNzQ1NDB9.PCIjiOy6zmSVm2ilrzlWZctmyBKIRnP1ECSP9G_O2mY

{
    "fullName": "new FullName",
    "email": "email@gmail.com",
    "password": "newPass"
}

###/api/test
GET {{host}}/api/test HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE4OTcyODZ9.r4_kQ4VCPss2xgoxuMdt2lXI-03xkmwboOD5tafUM-Q


### health check
GET {{host}}




# ------- project -------
###
POST {{host}}/api/project HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "name": "project 2",
  "type": "LANDING"
}

###
GET {{host}}/api/project?id=645a91c1b5d8c898fc762833 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
GET {{host}}/api/project/list HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###
PUT {{host}}/api/project HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

{
  "id": "645a908c6312bf0750cd6649",
  "name": "project new",
  "compressString": "hmmm"
}

###
DELETE  {{host}}/api/project?id=645a908c6312bf0750cd6649 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE5MDI5NjF9.Zaj0SMl--oKibmQQbe5h27jHVjqhG2AUBEJMiqalbrY

###