# -- user -- 

### sign up
POST http://localhost:3002/user-service/api/sign-up HTTP/1.1
content-type: application/json

{
    "fullName": "new user",
    "username": "newUser",
    "password": "dada"
}

### sign in
POST http://localhost:3002/user-service/api/sign-in HTTP/1.1
content-type: application/json

{
    "username": "newUser",
    "password": "newPass"
}

### get user
GET http://localhost:3002/user-service/api/user HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJleHAiOjIwNDIyNzQ1NDB9.PCIjiOy6zmSVm2ilrzlWZctmyBKIRnP1ECSP9G_O2mY


### update user
PUT http://localhost:3002/user-service/api/user HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJleHAiOjIwNDIyNzQ1NDB9.PCIjiOy6zmSVm2ilrzlWZctmyBKIRnP1ECSP9G_O2mY

{
    "fullName": "new FullName",
    "email": "email@gmail.com",
    "password": "newPass"
}

###/api/test
GET http://34.117.219.34/user-service/api/test HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdLRXVzZXIiLCJleHAiOjIwNDE4OTcyODZ9.r4_kQ4VCPss2xgoxuMdt2lXI-03xkmwboOD5tafUM-Q


### health check
GET http://localhost:3002 HTTP/1.1