HTTP:
    PORT: 3007

LOG:
  LEVEL: DEBUG
  DISABLE_COLORS: false
  REPORT_CALLER: true

MONGO_DB: mongodb+srv://thesis:thesisK19@thesis.kzystcv.mongodb.net

SERVICE_DB: file_management_service

GEN_CODE_HOST: localhost:9093