apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-mgt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-mgt-deployment
  template:
    metadata:
      labels:
        app: file-mgt-deployment
    spec:
      containers:
        - name: file-mgt-deployment
          image: asia-southeast1-docker.pkg.dev/buildify-388906/buildify-registry/file-mgt:19
          imagePullPolicy: IfNotPresent
          env:
            - name: jwt_secret
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_secret
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
