apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
      - env:
        - name: GEN_CODE_HOST
          value: gen-code-service:443
        image: asia-southeast1-docker.pkg.dev/thesis-378216/buildify-registry/user:bba08ce
        imagePullPolicy: Always
        name: user-deployment
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
