apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-deployment
          image: asia-southeast1-docker.pkg.dev/buildify-388906/buildify-registry/user:22
          imagePullPolicy: IfNotPresent
          env:
            - name: GEN_CODE_HOST
              value: gen-code-service:443
            - name: jwt_secret
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_secret
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
