export const PROPS_BY_ID = {
  Container_ROOT: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    fillSpace: "no",
    padding: ["40", "40", "40", "40"],
    margin: ["0", "0", "0", "0"],
    background: { r: 255, g: 255, b: 255, a: 1 },
    color: { r: 0, g: 0, b: 0, a: 1 },
    shadow: 0,
    radius: 0,
    width: "800px",
    height: "auto",
    styledClassNames: {},
  },
  Container_ePVPY3xZfA: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    fillSpace: "no",
    padding: ["40", "40", "40", "40"],
    margin: ["0", "0", "40", "0"],
    background: { r: 234, g: 245, b: 245, a: 1 },
    color: { r: 0, g: 0, b: 0, a: 1 },
    shadow: 0,
    radius: 0,
    width: "100%",
    height: "auto",
    styledClassNames: {},
  },
};
