SERVER:
  GRPC:
    PORT: 9091
  HTTP:
    PORT: 3002

LOG:
  LEVEL: DEBUG
  DISABLE_COLORS: false
  REPORT_CALLER: true

MONGO_DB: mongodb+srv://thesis:thesisK19@thesis.kzystcv.mongodb.net

SERVICE_DB: user_service
API_SECRET: Y1VFGSea2EPa6v3gFY84swUJbZCHY8WEzKfdq6uPUyRjYR
