export const PROPS_BY_ID = {
  ROOT_about: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    fillSpace: "no",
    padding: ["40", "40", "40", "40"],
    margin: ["0", "0", "0", "0"],
    background: { r: 255, g: 255, b: 255, a: 1 },
    color: { r: 0, g: 0, b: 0, a: 1 },
    shadow: 0,
    radius: 0,
    width: "100%",
    height: "auto",
    styledClassNames: {},
  },
  Text_SS0mt8wxyk: {
    fontSize: "22",
    textAlign: "left",
    fontWeight: "600",
    color: { r: "92", g: "90", b: "90", a: "1" },
    margin: ["0", "0", "0", "0"],
    shadow: 0,
    text: "About Page",
    styledClassNames: {},
    tagName: "h2",
  },
  Container_dmKjodcYHo: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    fillSpace: "no",
    padding: ["0", "0", "0", "0"],
    margin: ["0", "0", "0", "0"],
    background: { r: 200, g: 61, b: 61, a: 1 },
    color: { r: 0, g: 0, b: 0, a: 1 },
    shadow: 0,
    radius: 0,
    width: "300px",
    height: "300px",
    styledClassNames: {},
  },
  "Image_x-HJcZ61k6": {
    alt: "alternative description",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6o1MyYtFMFxk-9c62sOBJGi51LqxvlU4b1WKeTwqjOTu3aNdtJ83ITrp7Q0vEGn_f8zU&usqp=CAU",
    width: "400px",
    height: "200px",
    radius: 10,
    objectFit: "cover",
  },
  Button_HMwJyOTH_o: {
    fontSize: "14",
    textAlign: "center",
    fontWeight: "400",
    background: { r: "86", g: "163", b: "9", a: "1" },
    color: { r: "255", g: "255", b: "255", a: "1" },
    buttonStyle: "full",
    text: "Button",
    padding: ["10", "10", "10", "10"],
    margin: ["5", "0", "5", "0"],
    textComponent: {
      fontSize: "15",
      textAlign: "center",
      fontWeight: "500",
      color: { r: "92", g: "90", b: "90", a: "1" },
      margin: ["0", "0", "0", "0"],
      shadow: 0,
      text: "Text",
      styledClassNames: {},
      tagName: "h3",
    },
    width: "100%",
    height: "auto",
    styledClassNames: {},
  },
  Button_z_N1TpNJH8: {
    fontSize: "14",
    textAlign: "center",
    fontWeight: "400",
    background: { r: "22", g: "69", b: "209", a: "1" },
    color: { r: "255", g: "255", b: "255", a: "1" },
    buttonStyle: "full",
    text: "Button",
    padding: ["10", "10", "10", "10"],
    margin: ["5", "0", "5", "0"],
    textComponent: {
      fontSize: "15",
      textAlign: "center",
      fontWeight: "500",
      color: { r: "92", g: "90", b: "90", a: "1" },
      margin: ["0", "0", "0", "0"],
      shadow: 0,
      text: "Text",
      styledClassNames: {},
      tagName: "h3",
    },
    width: "50%",
    height: "auto",
    styledClassNames: {},
  },
  Button_l44yKBgA_4: {
    fontSize: "16",
    textAlign: "center",
    fontWeight: "400",
    background: { r: "197", g: "8", b: "41", a: "1" },
    color: { r: "255", g: "255", b: "255", a: "1" },
    buttonStyle: "full",
    text: "Block",
    padding: ["10", "10", "10", "10"],
    margin: ["5", "0", "5", "0"],
    textComponent: {
      fontSize: "15",
      textAlign: "center",
      fontWeight: "500",
      color: { r: "92", g: "90", b: "90", a: "1" },
      margin: ["0", "0", "0", "0"],
      shadow: 0,
      text: "Text",
      styledClassNames: {},
      tagName: "h3",
    },
    width: "50%",
    height: "auto",
    styledClassNames: {},
  },
  Video_s75Y21HcQK: { videoId: "6fWxJkhRKgk", width: "300px", height: "300px", enabled: false },
  Input_b7E1UXnuvX: {
    fontSize: "14",
    textAlign: "left",
    fontWeight: "500",
    background: { r: 255, g: 255, b: 255, a: 0.5 },
    color: { r: 0, g: 0, b: 0, a: 1 },
    borderColor: { r: 221, g: 223, b: 226, a: 1 },
    borderColorFocus: { r: 126, g: 176, b: 114, a: 1 },
    type: "text",
    inputStyle: "full",
    padding: ["10", "10", "10", "10"],
    margin: ["10", "0", "10", "0"],
    width: "300px",
    height: "50px",
    styledClassNames: {},
    inputOptions: { required: true, readonly: false },
    placeholder: "Input value here",
  },
};
